# Generated by Django 4.0.5 on 2022-06-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AARM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed AARM', max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed domain', max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed subdomain', max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='RawArmDataRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('additional', models.JSONField()),
                ('aarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.aarm')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractRewardRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reward', models.FloatField()),
                ('aarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.aarm')),
            ],
        ),
        migrations.AddField(
            model_name='aarm',
            name='sub_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.subdomain'),
        ),
    ]
