# Generated by Django 4.0.5 on 2022-06-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0004_rename_days_edition_interval_edition_ignoregaps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aarm',
            name='edition',
        ),
        migrations.AddField(
            model_name='abstractrewardregister',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experimentapp.edition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractrewardregister',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
