# Generated by Django 4.0.5 on 2022-06-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0007_experiment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iteration', models.IntegerField()),
                ('performance', models.FloatField()),
                ('reward', models.FloatField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimentapp.episodeexecution')),
            ],
        ),
    ]
