# Generated by Django 4.0.5 on 2022-06-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0009_alter_executionresult_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionresult',
            name='iteration',
        ),
    ]
