# Generated by Django 4.0 on 2022-07-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0011_executionresult_iteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experimentapp.aarm'),
            preserve_default=False,
        ),
    ]
